# -----------------------------------------------------------------------------
# Configuration file for the DecodingDD project
# -----------------------------------------------------------------------------
# This file centralizes paths for different computing environments.
# You can select an environment (e.g., 'local', 'hpc') when running a script.
# -----------------------------------------------------------------------------

local:
  # Paths for running on your local machine
  bids_dir: data
  derivatives_dir: derivatives
  fmriprep_dir: /Users/joshuabuckholtz/Data/UH1_Aim1/Derivatives/fMRIPrepped
  onsets_dir: /Users/joshuabuckholtz/Data/UH1_Aim1/Onsets

hpc:
  # Paths for running on the Stanford OAK HPC cluster
  # TODO: Update these paths to your specific OAK directories
  bids_dir: /oak/stanford/groups/russpold/data/uh2/aim1/BIDS/
  derivatives_dir: /oak/stanford/groups/russpold/users/buckholtz/Decoding_DD/output
  fmriprep_dir: /oak/stanford/groups/russpold/data/uh2/aim1/derivatives/fmriprep/
  onsets_dir: "/oak/stanford/groups/russpold/data/uh2/aim1/onsets"
  # Add other HPC-specific paths as needed

# ==============================================================================
# Analysis Parameters
# ==============================================================================
# These parameters are used across multiple analysis scripts to ensure consistency.
analysis_params:
  # GLM Parameters
  t_r: 2.0
  slice_time_ref: 0.5
  smoothing_fwhm: 5.0
  
  # Cross-validation parameters
  n_splits: 5
  random_state: 42
