# -----------------------------------------------------------------------------
# Configuration file for the DecodingDD project
# -----------------------------------------------------------------------------
# This file centralizes paths for different computing environments.
# You can select an environment (e.g., 'local', 'hpc') when running a script.
# -----------------------------------------------------------------------------

local:
  # Paths for running on your local machine
  bids_dir: data
  derivatives_dir: derivatives
  fmriprep_dir: /Users/joshuabuckholtz/Data/UH1_Aim1/Derivatives/fMRIPrepped
  onsets_dir: /Users/joshuabuckholtz/Data/UH1_Aim1/Onsets

hpc:
  # Paths for running on the Stanford OAK HPC cluster
  # TODO: Update these paths to your specific OAK directories
  bids_dir: /oak/stanford/groups/russpold/data/uh2/aim1/BIDS/
  derivatives_dir: /oak/stanford/groups/russpold/users/buckholtz/Decoding_DD/output
  fmriprep_dir: /oak/stanford/groups/russpold/data/uh2/aim1/derivatives/fmriprep/
  onsets_dir: /oak/stanford/groups/russpold/data/uh2/aim1/onsets
  # Add other HPC-specific paths as needed

# ==============================================================================
# Analysis Parameters
# ==============================================================================
# These parameters are used across multiple analysis scripts to ensure consistency.
analysis_params:
  # GLM Parameters
  t_r: 0.68 # in seconds
  # Reference slice for model timing, set to the middle of the TR (0.5).
  # This aligns the model with data that has been slice-time corrected
  # during preprocessing (e.g., by fMRIPrep), which is standard for
  # multiband sequences.
  slice_time_ref: 0.5
  # Spatial smoothing kernel (Full-Width at Half-Maximum) in mm.
  # This is applied ONLY to the standard GLM. MVPA and RSA are performed
  # on unsmoothed data to preserve fine-grained spatial patterns.
  smoothing_fwhm: 5.0
  
  # Cross-validation parameters
  n_splits: 5 # General CV splits, can be overridden by specific analyses
  random_state: 42

  # --- Task-Specific Parameters ---
  glm:
    hrf_model: 'glover'
    drift_model: 'cosine'
    contrasts:
      - decision
      - choice
      - SVchosen
      - SVunchosen
      - SVsum
      - SVdiff
  
  rsa:
    searchlight_radius: 8
    models:
      - choice
      - later_delay
      - SVchosen
      - SVunchosen
      - SVsum
      - SVdiff
  
  mvpa:
    # A list of all target variables to decode
    targets:
      - choice       # Will be run as classification
      - SVchosen     # Will be run as regression
      - SVunchosen   # Will be run as regression
      - SVsum        # Will be run as regression
      - SVdiff       # Will be run as regression
    
    # Parameters for classification tasks
    classification:
      estimator: 'svc'
      scoring: 'accuracy'
      cv_folds: 5
      
    # Parameters for regression tasks
    regression:
      estimator: 'svr'
      scoring: 'r2'
      cv_folds: 5
  
  behavioral_modeling:
    k_bounds: [0.000001, 1.0]
    tau_bounds: [0.000001, 5.0]
    initial_params: [0.01, 1.0]

# ==============================================================================
# MRI Acquisition Parameters
# ==============================================================================
mri_acquisition_params:
  sequence: "single-echo multi-band echo-planar imaging (EPI)"
  tr: 0.680 # in seconds
  multiband_factor: 8
  echo_time: 0.030 # in seconds
  flip_angle: 53 # in degrees
  field_of_view: 220 # in mm
  voxel_size: [2.2, 2.2, 2.2] # isotropic, in mm
  slices: 64
  multiband_source: "GE"
  phase_encoding_direction: "j"
